version: "3.7"

services:
    nextjs:
        build:
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        environment:
            - DATABASE_PATH=/app/data/sammwise.sqlite
        volumes:
            - sammwise-data:/app/data
        networks:
            - samm-network
        ports:
            - "127.0.0.1:3000:3000"

networks:
    samm-network:
        driver: bridge

volumes:
    sammwise-data:
